import {
  SiAmazonaws,
  SiAngular,
  SiAntdesign,
  SiBootstrap,
  SiCss3,
  SiD3Dotjs,
  SiExpress,
  SiFastapi,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJquery,
  SiMobx,
  SiMongodb,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiPusher,
  SiPython,
  SiReact,
  SiReactquery,
  SiRedux,
  SiShopify,
  SiSwr,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVisualstudiocode,
  SiVuedotjs,
} from "react-icons/si";
import { Blocks, Code2, Database, Wrench } from "lucide-react";

export const skillGroups = [
  {
    category: "Languages",
    icon: Code2,
    items: [
      { name: "HTML", icon: SiHtml5 },
      { name: "CSS", icon: SiCss3 },
      { name: "JavaScript", icon: SiJavascript },
      { name: "TypeScript", icon: SiTypescript },
      { name: "Python", icon: SiPython },
    ],
  },
  {
    category: "Frameworks and Libraries",
    icon: Blocks,
    items: [
      { name: "React.js", icon: SiReact },
      { name: "Next.js", icon: SiNextdotjs },
      { name: "Redux", icon: SiRedux },
      { name: "Redux Toolkit", icon: SiRedux },
      { name: "MobX", icon: SiMobx },
      { name: "Zustand", label: "Zu" },
      { name: "Angular", icon: SiAngular },
      { name: "Vue.js", icon: SiVuedotjs },
      { name: "Node.js", icon: SiNodedotjs },
      { name: "Express.js", icon: SiExpress },
      { name: "FastAPI", icon: SiFastapi },
      { name: "Jest", icon: SiJest },
      { name: "jQuery", icon: SiJquery },
      { name: "Bootstrap", icon: SiBootstrap },
      { name: "Tailwind CSS", icon: SiTailwindcss },
      { name: "D3.js", icon: SiD3Dotjs },
    ],
  },
  {
    category: "Databases",
    icon: Database,
    items: [
      { name: "MongoDB", icon: SiMongodb },
      { name: "MySQL", icon: SiMysql },
    ],
  },
  {
    category: "Developer Tools and Platforms",
    icon: Wrench,
    items: [
      { name: "SWR", icon: SiSwr },
      { name: "TanStack Query", icon: SiReactquery },
      { name: "Git", icon: SiGit },
      { name: "GitHub", icon: SiGithub },
      { name: "VS Code", icon: SiVisualstudiocode },
      { name: "Vercel", icon: SiVercel },
      { name: "Netlify", icon: SiNetlify },
      { name: "AWS", icon: SiAmazonaws },
      { name: "Ant Design", icon: SiAntdesign },
      { name: "Pub/Sub (Pusher)", icon: SiPusher },
      { name: "Shopify", icon: SiShopify },
    ],
  },
];
